### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yeKcim** [amv213/3D-Optics-Library#1]
If I want to use, modify and share my own release of your files. What is the license? (great job, btw)

**Comment by amv213** [comment]
Thanks @yeKcim !

I am not maintaining this library anymore on GitHub, but I have an updated and more complete version on GitLab:
https://gitlab.com/amv213/componentlibrary

I've released it under a Creative Commons Attribution-NonCommercial 4.0 International License.

Let me know if you can access it (if not I can update this GitHub repo if it's easier for you)

**Comment by yeKcim** [comment]
Thanks a lot for these answer!

I add your gitlab repository to my library list in https://github.com/yeKcim/my_optics_blend

I will probably share my own inkscape files, actually I have only blend files (and have only shared fiber ones for now)

**Comment by amv213** [comment]
**P.S.** I figured out how to mirror repos from GitLab to GitHub. This repo should now be mirroring the contents of the original repo on GitLab 🎉
